{"preconception": {
  "corticosteroidsbudesonide": "No known harm", "budesonideno": "", "budesonideyes": "safe","5-aminosalicylatesmesalamine": "safe","prednisoneyes": "caution","prednisoneno": "", "methylprednisoloneyes": "caution","methylprednisoloneno": "", "hydrocortisoneyes": "caution","hydrocortisoneno": "","5-aminosalicylatessulfasalazine": "safe", "mesalamineyes": "safe", "mesalamineno": "", "sulfasalazineyes": "safe", "sulfasalazineno": "","immunomodulatorimuran": "safe", "imuranyes": "safe", "imuranno": "", "immunomodulatorpurinethol": "safe", "purinetholyes": "safe", "purinetholno": "", "biologicsantiTnfs": "safe", "antiTnfsyes": "safe", "antiTnfsno": "", "calcineurinInhibitorcyclosporin": "safe", "cyclosporinyes": "safe", "cyclosporinno": "", "antibioticsciprofloxacin": "safe", "ciprofloxacinyes": "safe", "ciprofloxacinno": "", "antibioticsmetronidazole": "safe", "metronidazoleyes": "safe", "metronidazoleno": "", "antibioticspenicillin": "safe", "penicillinyes": "safe","penicillinno": "", "immunomodulatormethotrexate": "unsafe", "methotrexateyes": "unsafe", "methotrexateno": "","smallMoleculestofacitinib": "unsafe",
  "biologicsustekinumab": "unknown", "ustekinumabyes": "safe", "ustekinumabno": "","biologicsvedolizumab": "unknown", "vedolizumabyes": "safe", "vedolizumabno": "", "corticosteroidsprednisone": "caution", "corticosteroidsmethylprednisolone": "caution", "jakinhibitorsyes": "unsafe", "jakinhibitorsno": "", "corticosteroidshydrocortisone": "caution", "allopurinolyes": "caution", "allopurinolno": "", "immunomodulatorallopurinol": "caution", "s1pmodulatorsyes": "unsafe", "s1pmodulatorsno":"", "Il23inhibitorsyes": "safe", "Il23inhibitorsno": ""
},
"pregnant": {
  "corticosteroidsbudesonide": "safe", "budesonideyes": "safe", "budesonideno": "", "5-aminosalicylatesmesalamine": "safe", "mesalamineyes": "safe", "mesalamineno": "", "5-aminosalicylatessulfasalazine": "safe", "sulfasalazineyes": "safe", "sulfasalazineno": "", "immunomodulatorimuran": "safe", "imuranyes": "safe", "imuranno": "", "immunomodulatorpurinethol": "safe", "purinetholyes": "safe", "purinetholno": "", "biologicsantiTnfs": "safe", "antiTnfsyes": "safe", "antiTnfsno": "", "antibioticspenicillin": "safe", "penicillinyes": "safe", "penicillinno": "", "immunomodulatormethotrexate": "unsafe", "methotrexateyes": "unsafe", "methotrexateno": "", "smallMoleculestofacitinib": "unsafe", "jakinhibitorsyes": "unsafe", "jakinhibitorsno": "",
  "biologicsustekinumab": "unknown", "ustekinumabyes": "safe","ustekinumabno": "", "biologicsvedolizumab": "unknown","vedolizumabyes": "safe", "vedolizumabno": "",
  "corticosteroidsprednisone": "caution", "prednisoneyes": "caution", "prednisoneno": "", "corticosteroidsmethylprednisolone": "caution", "methylprednisoloneyes": "caution", "methylprednisoloneno": "", "corticosteroidshydrocortisone": "caution", "hydrocortisoneyes": "caution", "hydrocortisoneno": "", "immunomodulatorallopurinol": "caution", "allopurinolyes": "caution", "allopurinolno": "", "calcineurinInhibitorcyclosporin": "caution", "cyclosporinyes": "caution", "cyclosporinno": "", "antibioticsciprofloxacin": "caution", "ciprofloxacinyes": "safe", "ciprofloxacinno": "", "antibioticsmetronidazole": "caution", "metronidazoleyes": "safe", "metronidazoleno": "", "s1pmodulatorsyes": "unsafe", "s1pmodulatorsno":"", "Il23inhibitorsyes": "safe", "Il23inhibitorsno": ""
},
"breastfeeding": {
  "corticosteroidsbudesonide": "safe", "budesonideyes": "safe", "budesonideno": "", "5-aminosalicylatesmesalamine": "safe", "mesalamineyes": "safe", "mesalamineno": "",  "5-aminosalicylatessulfasalazine": "safe", "sulfasalazineyes": "safe", "sulfasalazineno": "", "immunomodulatorimuran": "safe", "imuranyes": "safe", "imuranno": "", "immunomodulatorpurinethol": "safe", "purinetholyes": "safe", "purinetholno": "", "biologicsantiTnfs": "safe", "antiTnfsyes": "safe", "antiTnfsno": "", "antibioticsciprofloxacin": "safe", "ciprofloxacinyes": "safe", "ciprofloxacinno": "", "immunomodulatormethotrexate": "unsafe", "methotrexateyes": "unsafe", "methotrexateno": "", "smallMoleculestofacitinib": "unsafe", "jakinhibitorsyes": "unsafe", "jakinhibitorsno": "",
  "biologicsustekinumab":"safe", "ustekinumabyes":"safe", "ustekinumabno":"", "biologicsvedolizumab":"safe", "vedolizumabyes":"safe", "vedolizumabno":"",
  "corticosteroidsprednisone": "caution", "prednisoneyes": "caution", "prednisoneno": "", "corticosteroidsmethylprednisolone": "caution", "methylprednisoloneyes": "caution", "methylprednisoloneno": "", "corticosteroidshydrocortisone": "caution", "hydrocortisoneyes": "caution", "hydrocortisoneno": "", "immunomodulatorallopurinol": "caution", "allopurinolyes": "caution", "allopurinolno": "", "calcineurinInhibitorcyclosporin": "caution", "cyclosporinyes": "caution", "cyclosporinno": "", "antibioticsmetronidazole": "caution", "metronidazoleyes": "caution", "metronidazoleno": "", "penicillinyes": "safe", "penicillinno": "", "s1pmodulatorsyes": "unsafe", "s1pmodulatorsno":"", "Il23inhibitorsyes": "safe", "Il23inhibitorsno": ""
},
"vaccinations": {
  "corticosteroidsbudesonide": "safe", "budesonideyes": "safe","budesonideno": "", "5-aminosalicylatesmesalamine": "safe", "mesalamineyes": "safe", "mesalamineno": "",  "5-aminosalicylatessulfasalazine": "safe", "sulfasalazineyes": "safe", "sulfasalazineno": "", "immunomodulatorimuran": "safe", "imuranyes": "safe", "imuranno": "", "immunomodulatorpurinethol": "safe", "allopurinolyes": "safe", "allopurinolno": "", "purinetholyes": "safe", "purinetholno": "", "calcineurinInhibitorcyclosporin": "safe", "cyclosporinyes": "safe", "cyclosporinno": "", "metronidazoleyes": "safe", "metronidazoleno": "","penicillinyes": "safe", "penicillinno": "", "ciprofloxacinyes": "safe", "ciprofloxacinno": "",
  "biologicsustekinumab": "unknown", "ustekinumabyes": "safe", "ustekinumabno": "", "biologicsvedolizumab": "unknown", "vedolizumabyes": "safe", "vedolizumabno": "", "methotrexateyes": "safe", "methotrexateno": "",  "smallMoleculestofacitinib": "unknown", "jakinhibitorsyes": "caution", "jakinhibitorsbno": "",
  "corticosteroidsprednisone": "caution", "prednisoneyes": "safe", "prednisoneno": "", "corticosteroidsmethylprednisolone": "caution",  "methylprednisoloneyes": "safe", "methylprednisoloneno": "", "corticosteroidshydrocortisone": "caution", "hydrocortisoneyes": "safe", "hydrocortisoneno": "", "biologicsantiTnfs": "caution", "antiTnfsyes": "safe",  "antiTnfsno": "", "s1pmodulatorsyes": "caution", "s1pmodulatorsno":"", "Il23inhibitorsyes": "caution", "Il23inhibitorsno": ""
},
"infections": {
  "corticosteroidsbudesonide": "safe", "budesonideyes": "safe", "budesonideno": "", "5-aminosalicylatesmesalamine": "safe", "mesalamineyes": "safe", "mesalamineno": "",  "5-aminosalicylatessulfasalazine": "safe", "sulfasalazineyes": "safe", "sulfasalazineno": "", "immunomodulatorimuran": "safe", "imuranyes": "safe", "imuranno": "", "immunomodulatorpurinethol": "safe", "purinetholyes": "safe", "purinetholno": "", "antiTnfsyes": "safe", "antiTnfsno": "", "calcineurinInhibitorcyclosporin": "safe", "cyclosporinyes": "safe", "cyclosporinno": "", "biologicsustekinumab": "unknown", "ustekinumabyes": "safe", "ustekinumabno": "", "biologicsvedolizumab": "safe", "vedolizumabyes": "safe", "vedolizumabno": "", "smallMoleculestofacitinib": "unknown", "jakinhibitorsyes": "safe", "jakinhibitorsno": "", "corticosteroidsprednisone": "caution", "prednisoneyes": "caution", "prednisoneno": "", "methylprednisoloneyes": "caution", "methylprednisoloneno": "", "methylprednisolonehydrocortisone": "caution", "methotrexateyes": "caution", "methotrexateno": "", "allopurinolyes": "safe", "allopurinolno": "", "metronidazoleyes": "safe", "metronidazoleno": "","penicillinyes": "safe", "penicillinno": "", "ciprofloxacinyes": "safe", "ciprofloxacinno": "","hydrocortisoneyes": "caution", "hydrocortisoneno": "", "s1pmodulatorsyes": "safe", "s1pmodulatorsno":"", "Il23inhibitorsyes": "safe", "Il23inhibitorsno": ""
}}
