{"preconception": {
  "corticosteroidsbudesonide": "safe", "budesonideno": "", "budesonideyes": "safe","5-aminosalicylatesmesalamine": "safe","prednisoneyes": "caution","prednisoneno": "", "methylprednisoloneyes": "caution","methylprednisoloneno": "", "hydrocortisoneyes": "caution","hydrocortisoneno": "","5-aminosalicylatessulfasalazine": "safe", "mesalamineyes": "safe", "mesalamineno": "", "sulfasalazineyes": "safe", "sulfasalazineno": "","immunomodulatorimuran": "safe", "imuranyes": "safe", "imuranno": "", "immunomodulatorpurinethol": "safe", "purinetholyes": "safe", "purinetholno": "", "biologicsantiTnfs": "safe", "antiTnfsyes": "safe", "antiTnfsno": "", "calcineurinInhibitorcyclosporin": "safe", "cyclosporinyes": "safe", "cyclosporinno": "", "antibioticsciprofloxacin": "safe", "ciprofloxacinyes": "safe", "ciprofloxacinno": "", "antibioticsmetronidazole": "safe", "metronidazoleyes": "safe", "metronidazoleno": "", "antibioticspenicillin": "safe", "penicillinyes": "safe","penicillinno": "", "immunomodulatormethotrexate": "unsafe", "methotrexateyes": "unsafe", "methotrexateno": "","smallMoleculestofacitinib": "unsafe",
  "biologicsustekinumab": "unknown", "ustekinumabyes": "unknown", "ustekinumabno": "","biologicsvedolizumab": "unknown", "vedolizumabyes": "unknown", "vedolizumabno": "", "corticosteroidsprednisone": "caution", "corticosteroidsmethylprednisolone": "caution", "tofacitinibyes": "unsafe", "tofacitinibno": "", "corticosteroidshydrocortisone": "caution", "allopurinolyes": "caution", "allopurinolno": "", "immunomodulatorallopurinol": "caution"
},
"pregnant": {
  "corticosteroidsbudesonide": "safe", "budesonideyes": "safe", "budesonideno": "", "5-aminosalicylatesmesalamine": "safe", "mesalamineyes": "safe", "mesalamineno": "", "5-aminosalicylatessulfasalazine": "safe", "sulfasalazineyes": "safe", "sulfasalazineno": "", "immunomodulatorimuran": "safe", "imuranyes": "safe", "imuranno": "", "immunomodulatorpurinethol": "safe", "purinetholyes": "safe", "purinetholno": "", "biologicsantiTnfs": "safe", "antiTnfsyes": "safe", "antiTnfsno": "", "antibioticspenicillin": "safe", "penicillinyes": "safe", "penicillinno": "", "immunomodulatormethotrexate": "unsafe", "methotrexateyes": "unsafe", "methotrexateno": "", "smallMoleculestofacitinib": "unsafe", "tofacitinibyes": "unsafe", "tofacitinibno": "",
  "biologicsustekinumab": "unknown", "ustekinumabyes": "unknown","ustekinumabno": "", "biologicsvedolizumab": "unknown","vedolizumabyes": "unknown", "vedolizumabno": "",
  "corticosteroidsprednisone": "caution", "prednisoneyes": "caution", "prednisoneno": "", "corticosteroidsmethylprednisolone": "caution", "methylprednisoloneyes": "caution", "methylprednisoloneno": "", "corticosteroidshydrocortisone": "caution", "hydrocortisoneyes": "caution", "hydrocortisoneno": "", "immunomodulatorallopurinol": "caution", "allopurinolyes": "caution", "allopurinolno": "", "calcineurinInhibitorcyclosporin": "caution", "cyclosporinyes": "caution", "cyclosporinno": "", "antibioticsciprofloxacin": "caution", "ciprofloxacinyes": "safe", "ciprofloxacinno": "", "antibioticsmetronidazole": "caution", "metronidazoleyes": "caution", "metronidazoleno": ""
},
"breastfeeding": {
  "corticosteroidsbudesonide": "safe", "budesonideyes": "safe", "budesonideno": "", "5-aminosalicylatesmesalamine": "safe", "mesalamineyes": "safe", "mesalamineno": "",  "5-aminosalicylatessulfasalazine": "safe", "sulfasalazineyes": "safe", "sulfasalazineno": "", "immunomodulatorimuran": "safe", "imuranyes": "safe", "imuranno": "", "immunomodulatorpurinethol": "safe", "purinetholyes": "safe", "purinetholno": "", "biologicsantiTnfs": "safe", "antiTnfsyes": "safe", "antiTnfsno": "", "antibioticsciprofloxacin": "safe", "ciprofloxacinyes": "safe", "ciprofloxacinno": "", "immunomodulatormethotrexate": "unsafe", "methotrexateyes": "unsafe", "methotrexateno": "", "smallMoleculestofacitinib": "unsafe", "tofacitinibyes": "unsafe", "tofacitinibno": "",
  "biologicsustekinumab":"unknown", "ustekinumabyes":"unknown", "ustekinumabno":"", "biologicsvedolizumab":"unknown", "vedolizumabyes":"unknown", "vedolizumabno":"",
  "corticosteroidsprednisone": "caution", "prednisoneyes": "caution", "prednisoneno": "", "corticosteroidsmethylprednisolone": "caution", "methylprednisoloneyes": "caution", "methylprednisoloneno": "", "corticosteroidshydrocortisone": "caution", "hydrocortisoneyes": "caution", "hydrocortisoneno": "", "immunomodulatorallopurinol": "caution", "allopurinolyes": "caution", "allopurinolno": "", "calcineurinInhibitorcyclosporin": "caution", "cyclosporinyes": "caution", "cyclosporinno": "", "antibioticsmetronidazole": "caution", "metronidazoleyes": "caution", "metronidazoleno": ""
},
"vaccinations": {
  "corticosteroidsbudesonide": "safe", "budesonideyes": "safe","budesonideno": "", "5-aminosalicylatesmesalamine": "safe", "mesalamineyes": "safe", "mesalamineno": "",  "5-aminosalicylatessulfasalazine": "safe", "sulfasalazineyes": "safe", "sulfasalazineno": "", "immunomodulatorimuran": "safe", "imuranyes": "safe", "imuranno": "", "immunomodulatorpurinethol": "safe", "purinetholyes": "safe", "purinetholno": "", "calcineurinInhibitorcyclosporin": "safe", "cyclosporinyes": "safe", "cyclosporinno": "",
  "biologicsustekinumab": "unknown", "ustekinumabyes": "unknown", "ustekinumabno": "", "biologicsvedolizumab": "unknown", "vedolizumabyes": "unknown", "vedolizumabno": "", "methotrexateyes": "safe", "methotrexateno": "",  "smallMoleculestofacitinib": "unknown", "tofacitinibyes": "unknown", "tofacitinibno": "",
  "corticosteroidsprednisone": "caution", "prednisoneyes": "caution", "prednisoneno": "", "corticosteroidsmethylprednisolone": "caution",  "methylprednisoloneyes": "caution", "methylprednisoloneno": "", "corticosteroidshydrocortisone": "caution", "hydrocortisoneyes": "caution", "hydrocortisoneno": "", "biologicsantiTnfs": "caution", "antiTnfsyes": "caution",  "antiTnfsno": ""
},
"infections": {
  "corticosteroidsbudesonide": "safe", "budesonideyes": "safe", "budesonideno": "", "5-aminosalicylatesmesalamine": "safe", "mesalamineyes": "safe", "mesalamineno": "",  "5-aminosalicylatessulfasalazine": "safe", "sulfasalazineyes": "safe", "sulfasalazineno": "", "immunomodulatorimuran": "safe", "imuranyes": "safe", "imuranno": "", "immunomodulatorpurinethol": "safe", "purinetholyes": "safe", "purinetholno": "", "antiTnfsyes": "safe", "antiTnfsno": "", "calcineurinInhibitorcyclosporin": "safe", "cyclosporinyes": "safe", "cyclosporinno": "", "biologicsustekinumab": "unknown", "ustekinumabyes": "unknown", "ustekinumabno": "", "biologicsvedolizumab": "unknown", "vedolizumabyes": "unknown", "vedolizumabno": "", "smallMoleculestofacitinib": "unknown", "tofacitinibyes": "unknown", "tofacitinibno": "", "corticosteroidsprednisone": "caution", "prednisoneyes": "caution", "prednisoneno": "", "methylprednisolonehydrocortisone": "caution", "hydrocortisoneyes": "caution", "hydrocortisoneno": ""
}}
